name: CI
'on':
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch: null
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Copy Files to Deployment
        run: 'Xcopy /e /i /y * C:\Deployment\'
      - name: Run TOSCA Test
        run: 'C:\github\ToscaCI\Client\ToscaCIClient.exe -m distributed -c "C:\github\ToscaCI\Client\CITestExecConfig.xml" -r "C:\gitHub\Results\Result.xml"'
      - name: Test Report
        uses: dorny/test-reporter@v1.5.0
        if: success() || failure()
        with:
          name: "Unit test report"
          path: 'C:\gitHub\Results\Result.xml'
          reporter: java-junit
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Unit Test Results
          path: 'C:\gitHub\Result\Result.xml'


